lr="${lr:-0.01}"
batch_size="${batch_size:-1024}"
dnn=alexnet
dataset=imagenet
max_epochs="${max_epochs:-2}"
nstepsupdate=1
data_dir=/datasets/ILSVRC2012_dataset
#data_dir=/localdata/ILSVRC2012_dataset
