wandb_version: 1

batch_size:
  desc: null
  value: 128
nsteps_update:
  desc: null
  value: 1
nworkers:
  desc: null
  value: 4
nwpernode:
  desc: null
  value: 4
dataset:
  desc: null
  value: cifar10
dnn:
  desc: null
  value: resnet20
data_dir:
  desc: null
  value: /home/comp/amelieczhou/datasets/cifar10/
saved_dir:
  desc: null
  value: ./logs/tzc
lr:
  desc: null
  value: 0.1
max_epochs:
  desc: null
  value: 181
pretrain:
  desc: null
  value: null
num_steps:
  desc: null
  value: 35
compressor:
  desc: null
  value: none
density:
  desc: null
  value: 1.0
threshold:
  desc: null
  value: 524288000
momentum_correction:
  desc: null
  value: 0
strategy:
  desc: null
  value: average
overlap_scalar:
  desc: null
  value: 2.0
nsteps_localsgd:
  desc: null
  value: 20
optimizer_name:
  desc: null
  value: SGD
gaussian_mu:
  desc: null
  value: 0.0
gaussian_std:
  desc: null
  value: 0.001
add_noise:
  desc: null
  value: true
alg:
  desc: null
  value: sgd
local_rank:
  desc: null
  value: 0
sync:
  desc: null
  value: avg
wandb_offline:
  desc: null
  value: false
wandb_console:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: hpml-hkbu
wandb_key:
  desc: null
  value: 5edd8acc594b95a0b4f58e39b2243143f03c65a0
exp_abs_path:
  desc: null
  value: .
project_name:
  desc: null
  value: DDP-Train
exp_name:
  desc: null
  value: sgd-noiTrue-std0.001-resnet20-SGD-lr0.1
override_cmd_args:
  desc: null
  value: false
tag:
  desc: null
  value: debug
exp_tool_init_sub_dir:
  desc: null
  value: 'no'
enable_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719163222
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.17.2
      8:
      - 5
      13: linux-x86_64
